import QtQuick 2.0
import QtTest 1.0
import Testable 1.0
import "../samples/sprintf.js" as SPrintf
import "../samples/lodash.merge.js" as LodashMerge
Item {
    id: window
    height: 640
    width: 480

    TestCase {
        name: "QmlTests"

        function test_sprintf() {
            // Test the sprintf generated by this program
            compare(SPrintf.sprintf("%d %d",1,2), "1 2");
        }

        function test_lodashMerge() {
            var input = {
                value1: 1,
                value2: 2.0
            }

            var output = LodashMerge.lodashMerge({}, input);

            compare(output.value1, 1);
            compare(output.value2, 2.0);

        }



    }
}
