import QtQuick 2.0
import QtTest 1.0
import Testable 1.0
import "../samples/sprintf.js" as SPrintf

Item {
    id: window
    height: 640
    width: 480

    TestCase {
        name: "QmlTests"

        function test_sprintf() {
            // Test the sprintf generated by this program
            compare(SPrintf.sprintf("%d %d",1,2), "1 2");
        }
    }
}
